# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_private', models.BooleanField(default=True)),
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
