# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='password',
            field=models.CharField(default='', max_length=60),
        ),
    ]
